### ISSUE TITLE
Great work! But should contribute to the original project

### ISSUE THREAD

**Issue by liangqi** [cwc1987/QmlBook-In-Chinese#10]
There are de, it, pt sub directories for translation contribution under https://github.com/qmlbook/qmlbook . So you should create a zh or zh_cn there.

**Comment by OnceMore2020** [comment]
> "For this clone the repository and then later create a pull request that we can sort this in."

https://github.com/qmlbook/qmlbook/blob/master/CONTRIBUTING.md#translations

**Comment by cwc1987** [comment]
Hi, I see it, the original project use sphinx to build book, I need spend some time on it.
