### ISSUE TITLE
书中的代码及资源文件如何获取？

### ISSUE THREAD

**Issue by gkzscs** [cwc1987/QmlBook-In-Chinese#20]
`1.2.2章节`中，出现的风车背景图`images/background.png`，该图片如何获取？

**Comment by kangshuaibing** [comment]
同问

**Comment by kangshuaibing** [comment]
> `1.2.2章节`中，出现的风车背景图`images/background.png`，该图片如何获取？

找到了：https://qmlbook.github.io/assets/
