### ISSUE TITLE
中文用词不准确

### ISSUE THREAD

**Issue by tlexy** [cwc1987/QmlBook-In-Chinese#9]
首先楼主翻译辛苦啦，但这书从一开始我就看不下去啦。。。。。。
markup language一般都是翻译为标记语言，而不是标识...不过我想你应该明白，但为什么要翻译为标识呢？
接下来就是你的用词和造句了，实在是看不下去。。。病句到处都是。。。读起来很有问题。

**Comment by cwc1987** [comment]
非常感谢，我的英语确实比较渣哈，最近还没时间做矫正，后续我会根据你的建议修改的，如果还发现其它的问题，欢迎随时提出~
